owner: navikt
repos:
  - reponame:
      - flex-slack-metrikker
    checks:
      - Bygg, test og publiser docker image

  - reponame:
      - flex-arkitektur
      - flex-bigquery-soda
      - flex-bigquery-terraform
      - flex-datafortelling
      - flex-quarto-template
      - flex-slack-reminders
      - flexjar-infoskjerm
      - omrade-helse-etterlevelse-topic
      - terraform-google-bigquery-datastream

  - reponame:
      - flex-internal-frontend
      - flex-testdata-generator
    checks:
      - felles-workflow / Bygg, test og publiser docker image

  - reponame:
      - flexjar-frontend
    checks:
      - felles-workflow / Bygg, test og publiser docker image
      - playwright

  - reponame:
      - ditt-sykefravaer-backend
      - flex-arbeidssokerregister-oppdatering
      - flex-auditlogger
      - flex-brreg-proxy
      - flex-inntektsmelding-status
      - flex-joark-mottak
      - flex-syketilfelle
      - flex-sykmeldinger-backend
      - flexjar-backend
      - spinnsyn-arkivering
      - spinnsyn-backend
      - spinnsyn-brukernotifikasjon
      - syfosoknadbrukernotifikasjon
      - sykepengesoknad-altinn
      - sykepengesoknad-arkivering-oppgave
      - sykepengesoknad-backend
      - sykepengesoknad-ikke-sendt-altinnvarsel
      - sykepengesoknad-kvitteringer
      - sykepengesoknad-narmesteleder-varsler
    checks:
      - felles-workflow / Bygg og publiser
      - felles-workflow / Lint
      - felles-workflow / Test

  - reponame:
      - ditt-sykefravaer
      - spinnsyn-frontend
      - sykepengesoknad-frontend
    checks:
      - felles-workflow / Bygg, test og publiser docker image
      - felles-workflow / playwright (1, 4)
      - felles-workflow / playwright (2, 4)
      - felles-workflow / playwright (3, 4)
      - felles-workflow / playwright (4, 4)
      - felles-workflow / lint
      - felles-workflow / unit-test

  - reponame:
      - flex-sykepengesoknad-pdfgen
    checks:
      - Bygg, test og publiser docker image

  - reponame:
      - flex-alerts
      - flex-github-actions-workflows
      - sykepengesoknad-kafka

  - reponame:
      - flex-cli
    checks:
      - Bygg og lint
